name: PortfolioFy
author: Kaustubh Gupta  
description: Creates an webpage which can be deployed as Github page
inputs:
  gh_token:
    description: "Github Personal Access token"
    required: True
    default: ${{ github.secrets.GITHUB_TOKEN }}
  theme:
    description: "Type of webpage you want to render"
    required: False
    default: 1
  blogs:
    description: "Include blogs in your Portfolio"
    required: False
    default: False
  hackathons:
    description: "Include hackathon projects."
    required: False
    default: False
  stats_choice: 
    description: "Type of GitHub Stats"
    required: False
    default: 1
  stats_customization:
    description: "Custom parameters for the GitHub stats choosen"
    required: False
    default: False
  current_repo_path:
    description: "Path of the current Repo"
    required: False
    default: ${{ github.workspace }}
  current_repo_branch:
    description: "Name of the current branch"
    required: False
    default: ${{ github.ref }}
  resume_link:
    description: "Link for resume pdf uploaded online"
    required: False
    default: False
  allow_footer:
    description: "Display Creator Credits"
    required: False
    default: True
  project_sort_by:
    description: "Sorting the projects according to count of number of stars or forks"
    required: False
    default: 'stars'
  social_links:
    description: "Linkedin, Twitter, Stackoverflow, Medium, Devto"
    required: False
    default: False

runs:
  using: "composite"
  steps:
    - run: python -m pip install PyGithub
      shell: bash
    - run: python ${{ github.action_path }}/generate_index.py ${{ inputs.gh_token }} ${{ inputs.theme }} ${{ inputs.blogs }} ${{ inputs.hackathons }} ${{ inputs.stats_choice }} ${{ inputs.current_repo_path }} ${{ inputs.current_repo_branch }} ${{ inputs.resume_link }} ${{ inputs.allow_footer }} ${{ inputs.project_sort_by }} ${{ inputs.stats_customization }} ${{ inputs.social_links }} 
      shell: pwsh
branding:
  icon: "award"
  color: "green"
